### ISSUE TITLE
conflict for bext instruction

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-bitmanip#107]
I think I'm misunderstanding one of the recent changes to instruction names in version 0.93. What was originally single-bit instruction `sbext` has been renamed `bext` (section 2.1.7). However, there is already a `bext` with different semantics (section 2.5).

Can you please clarify?

Thanks.

**Comment by kito-cheng** [comment]
Yes, it's known issue/bug in the `0.93` and it fixed on [`0.94-draft`](https://github.com/riscv/riscv-bitmanip/commit/d2eaf97c14bcc99175c3dbf6cacf17151475735b), hopeful we can have `0.94` soon...

**Comment by JamesKenneyImperas** [comment]
ok, thanks. closing.
