### ISSUE TITLE
Table 2.1 omits slo, sloi, sro and sroi

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-bitmanip#109]
Instructions `slo`, `sloi`, `sro` and `sroi` are not listed in any subset in table 2.1.

**Comment by kdockser** [comment]
These instructions have been dropped from inclusion in the extension based on the belief that they are never used by compilers. I will add all such dropped instructions to a new section of the specification along with comments as to why they were given the axe. That way they can be revived at a later date should someone come up with a compelling case.

**Comment by JamesKenneyImperas** [comment]
Thanks. Can you append to this issue when you are done?

**Comment by ptomsich** [comment]
Addressed in 1.0.0.
