### ISSUE TITLE
Wrong description of logical with negate andn instruction

### ISSUE THREAD

**Issue by M-Ijaz-10x** [riscv/riscv-bitmanip#173]
Hi @ptomsich, @aswaterman,
I was going through the bitmanip public review specification and I found that the andn instruction from logical with negate group has the wrong description, the description says that we need to perform bitwise logical and, which should either be bitwise or logical and not bitwise logical and.
Thanks.

**Comment by aswaterman** [comment]
For better or worse, “bitwise logical” unambiguously means “bitwise”. This may be a divergence between C language parlance and computer-architecture parlance, but there’s no bug here.

**Comment by M-Ijaz-10x** [comment]
Thanks @aswaterman for clearing the point
