### ISSUE TITLE
Name confusion: CPOP

### ISSUE THREAD

**Issue by tovine** [riscv/riscv-bitmanip#174]
I realize this is probably way too late to change at this point, but having the name `CPOP` (instead of `POPCNT` or similar) is at risk of causing confusion and mixup with the `cm.pop` instruction from the [Zce (code size reduction) extension](https://github.com/riscv/riscv-code-size-reduction/blob/V0.70.1-TOOLCHAIN-DEV/Zce-release-candidate/cm_pop.adoc).

It was worse back when the instruction was called `c.pop`, but they're still pretty similar...
I don't have any hopes of changing this now, but just wanted to make sure you're aware.

**Comment by ptomsich** [comment]
With Zbb ratified, the mnemonic can't be changed reasonably.  I would recommend that you raise this issue with the Zce group and (if not addressed to your satisfaction) comment during public review of Zce.
