### ISSUE TITLE
Does MISA.B control zba/zbb/zbc/zbs?

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-bitmanip#183]
We are implementing the bit-manipulation extension, do we then implement the B bit in the MISA CSR? The privileged spec says that the B bit is reserved and must return zero on read.

**Comment by pdonahue-ventana** [comment]
No.  misa.B was previously going to be used for the B extension but it is now (in the ratified priv spec) a reserved bit.  There is no B extension, just a group of Zb* extensions which are not related to the B bit.

**Comment by jrahmeh** [comment]
Thanks for the quick reply.  Closing.
