### ISSUE TITLE
Make instruction names consistent for B and V extensions

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-bitmanip#21]
In a few instances, the current drafts for the B and V extensions have instructions that give different names to the same operation.

The B extension has PCNT, while the V extension has an instruction called VMPOPC, where "POPC" also stands for *population count*.

The B extension has ANDC, while the V extension has VMANDNOT and VMORNOT.

For the examples above, one or the other extension (or both) must be changed to avoid gratuitous inconsistencies.

Furthermore, the B extension has CMOV, while the V extension has VMERGE that performs the same function element-wise for vectors.  (My preference would be to have SELECT and VSELECT, or SEL and VSEL, but if those are impossible, I propose renaming CMOV as MERGE.)

Finally, the B extension has BEXT which operates on bits, while the V extension has VCOMPRESS that performs the same function on vector elements.

**Comment by cliffordwolf** [comment]
I'll raise those issues on the V-extension mailing list.
