### ISSUE TITLE
Need better support for signed bytes and halfwords?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-bitmanip#23]
With the current draft of the B extension, RISC-V has single instructions that can be used to zero-extend a byte (ANDI), halfword (PACKW), or word (PACK or ADDIWU) to full 64-bit register width.  A word can also be sign-extended in one instruction (ADDIW).  But, unless I'm mistaken, there is still no single instruction that can sign-extend a byte or halfword to 64 bits.  If there are constituencies out there that make frequent use of signed `char` and `short` types (embedded applications with limited memory, perhaps?), such instructions might get more use overall than others that are being included.

Similarly, for reading big-endian data, we currently have the ability in only two instructions to load and byte-swap an unsigned halfword (LHU + BSWAP.H), an unsigned word (LWU + BSWAP.W), or a signed word (LWU + GREVIW), but not a signed halfword, which takes three instructions.

**Comment by cliffordwolf** [comment]
See my full statement here: https://lists.riscv.org/g/tech-bitmanip/message/394
