### ISSUE TITLE
grev/grevi issue with rs2 vs imm

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-bitmanip#30]
It starts off by listing both grev ... rs2 and grevi ... imm.

Then the first paragraph says "It takes in a single register value and an immediate ..." which conflicts with the above and suggests the last operand must be an immediate.

Then the second paragraph says "This operation iteratively checks each bit i in rs2 ..." which suggests that the last operand must be a register.

**Comment by cliffordwolf** [comment]
Thanks. Also added the missing `log2()` to the 2nd paragraph.
