### ISSUE TITLE
Problem with installing the bit manipulation gcc compiler

### ISSUE THREAD

**Issue by amedoc** [riscv/riscv-bitmanip#37]
Hello guys, 
last day I struggled with building the bit manipulation patch for gcc compiler. when running the following command bash gcc-build.sh and after of course configuring the shell file. I face this error of missing configuration 
![bit-manip](https://user-images.githubusercontent.com/51352187/61532356-dc6ca700-aa29-11e9-8d11-b138660a16bf.png)

**Comment by cliffordwolf** [comment]
That's weird because that's not what gcc-build.sh does:

```
mkdir gcc-build
cd gcc-build
../gcc-9.1.0/configure --prefix=/opt/riscv64b --target=riscv64-unknown-elf --enable-languages=c --disable-libssp
```

I have no idea why you seem to have `./configure [..]` in your copy of `gcc-build.sh` instead.
