### ISSUE TITLE
ANDC Bit Encoding

### ISSUE THREAD

**Issue by Keith-Cancel** [riscv/riscv-bitmanip#4]
So I was looking at the encoding a lot are not fully described, but this one seems obvious too me.
`| ??????? | rs2 | rs1 | ??? | rd | 0110011 | ANDC `

Here is the current AND:
`| 0000000 | rs2 | rs1 | 111 | rd | 0110011 | AND`

Why not define ANDC much like Shift Right and Arithmetic shift right. Also ADD
to SUB is very similar. So using this bit to denote negation seems pretty intuitive. 
`| 0100000 | rs2 | rs1 | 111 | rd | 0110011 | ANDC`

While probably not as useful ANDC it's also logical easy to extend the complemented
inputs for the other bitwise instructions like this.
```
| 0100000 | rs2 | rs1 | 100 | rd | 0110011 | XORC
| 0100000 | rs2 | rs1 | 110 | rd | 0110011 | ORC
```

Also when it comes to hardware implementation negation is used when converting a positive number to a negative number (2's complement). Therefore, it would be easy to use the same negation hardware if the same bit was used to denote negation.  Also keeping func3 the same means an ALU only has worry about choosing to negate an input.

**Comment by Keith-Cancel** [comment]
Sadly, there is no spare space for an ANDCI in the ANDI instruction. However, you usually are using bit masks that occupy a large portion of machine word. So not sure that is really much benefit.

**Comment by cliffordwolf** [comment]
Are you looking at an old version of the document? Because in the current version ANDC is defined exactly like you suggest:

![image](https://user-images.githubusercontent.com/619764/56467438-2809b780-641f-11e9-8be7-bce61c1e54a2.png)

![image](https://user-images.githubusercontent.com/619764/56467448-3d7ee180-641f-11e9-9bac-c14ab334aa9d.png)

> it's also logical easy to extend the complemented inputs for the other bitwise instructions like this

we did and early evaluation on this over a year ago and it looks like there is very little to gain by doing this.

**Comment by Keith-Cancel** [comment]
Woops, I should have looked a little more closely. The copy I have saved local has the same version number, but obviously there are differences. Should have looked at the date. 

![version](https://user-images.githubusercontent.com/8355441/56467960-34891280-6415-11e9-8a21-ef0d91710aef.png)

**Comment by Keith-Cancel** [comment]
Also the only time I have found the other complements would be useful is when bit slicing for constant time crypto. ANDC is handy also for muxing though.

**Comment by cliffordwolf** [comment]
> [..] has the same version number [..]

"0.37-draft" just means somewhere between 0.36 and 0.37.  :)

**Comment by Keith-Cancel** [comment]
I will keep that in mind.
