### ISSUE TITLE
Missing library file "vsupport.h"

### ISSUE THREAD

**Issue by federicorossifr** [riscv/riscv-bitmanip#57]
I'm trying to compile examples with the compiled toolchain from the riscv repository. However, I could not find the said file in any repository here. From where does it come from?

**Comment by jim-wilson** [comment]
It is the riscv-ovpsim vector examples that use vsupport.h, and there is no vector support on the bitmanip branch.  It is a separate unrelated draft extension.  Just ignore the vector stuff.  There isn't any useful compiler support for it yet.

**Comment by federicorossifr** [comment]
Thank you for your reply.

**Comment by dovedevic** [comment]
I'm looking to benchmark some vector instructions with an application in mind. Is this still the case? Currently using the `riscv64-unknown-elf-gcc` compiler. Any chance at understanding what `enableVEC()` does explicitly, as well as the types `v512P, v512T, VEC32, and Uns32`?

**Comment by jim-wilson** [comment]
This is still not the vector extension.  The imperas simulator apparently has some vector support, but you would have to ask them.

**Comment by LarryImperas** [comment]
Readme for riscvOVPsim shows full support for the vector instructions:  https://github.com/riscv/riscv-compliance/blob/master/riscv-ovpsim/README.md.  riscvOVPsim can be used as an ISS, however, it has some limitations in functionality.  If you run into those, try the full OVPsim simulator from the Open Virtual Platforms website.  You can start here:  https://www.ovpworld.org/info_riscv.
