### ISSUE TITLE
Doesn't work sh1addu.w

### ISSUE THREAD

**Issue by kropotin4** [riscv/riscv-bitmanip#59]
In rvb_simple EU:
When execute sh1addu.w shadd_active == 1 and wuw_active == 1 at the same time. 
So rd = shadd_out | wuw_dout.

wuw_dout == 1 because din_insn14 == 0. So din_insn14 == 1 in sh2addu.w and sh3addu.w  and they work.

**Comment by cliffordwolf** [comment]
Ooops! Thanks for reporting this issue. Fixed in 9da4644.
