### ISSUE TITLE
Error while building GCC

### ISSUE THREAD

**Issue by sopmacF** [riscv/riscv-bitmanip#73]
I'm facing problems when building the GCC.
Any ideas?
Thx in advance!

_g++ -c   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H  -DGENERATOR_FILE -fno-PIE -I. -Ibuild -I../../riscv-gcc/gcc -I../../riscv-gcc/gcc/build -I../../riscv-gcc/gcc/../include  -I../../riscv-gcc/gcc/../libcpp/include  \
	-o build/vec.o ../../riscv-gcc/gcc/vec.c
../../riscv-gcc/gcc/doc/invoke.texi:1791: unknown command 'github'
../../riscv-gcc/gcc/doc/invoke.texi:1791: @include: could not find /home/sopmac/Desktop/phd/git/riscv-bitmanip/tools/riscv-gcc-build/gcc/../../riscv-gcc/gcc/../libiberty/at-file.texi
make[2]: *** [Makefile:3230: doc/gcc.info] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '<PATH>/riscv-bitmanip/tools/riscv-gcc-build/gcc'
make[1]: *** [Makefile:4351: all-gcc] Error 2
make[1]: Leaving directory '<PATH>/riscv-bitmanip/tools/riscv-gcc-build'
make: *** [Makefile:952: all] Error 2_

Here the results of configure:

_checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... riscv64-unknown-elf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln works... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... gawk
checking for libatomic support... no
checking for libitm support... no
checking for libsanitizer support... no
checking for libvtv support... no
checking for libhsail-rt support... no
checking for libphobos support... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ accepts -static-libstdc++ -static-libgcc... yes
checking for gnatbind... no
checking for gnatmake... no
checking whether compiler driver understands Ada... no
checking how to compare bootstrapped objects... cmp --ignore-initial=16 $$f1 $$f2
checking for objdir... .libs
checking for the correct version of gmp.h... yes
checking for the correct version of mpfr.h... yes
checking for the correct version of mpc.h... yes
checking for the correct version of the gmp/mpfr/mpc libraries... yes
checking for isl 0.15 or later... no
required isl version is 0.15 or later
The following languages will be built: c,c++,fortran,lto,objc
*** This configuration is not supported in the following subdirectories:
     target-libgomp target-libatomic target-libitm target-libsanitizer target-libvtv target-libphobos gnattools gotools target-libada target-libhsail-rt target-zlib target-libgo target-libffi target-liboffloadmic target-libssp
    (Any other directories should still work fine.)
checking for default BUILD_CONFIG... 
checking for --enable-vtable-verify... no
*** removing build-x86_64-pc-linux-gnu/libiberty/Makefile to force reconfigure
*** removing build-x86_64-pc-linux-gnu/libcpp/Makefile to force reconfigure
*** removing build-x86_64-pc-linux-gnu/fixincludes/Makefile to force reconfigure
*** removing intl/Makefile to force reconfigure
*** removing libiberty/Makefile to force reconfigure
*** removing zlib/Makefile to force reconfigure
*** removing libbacktrace/Makefile to force reconfigure
*** removing libcpp/Makefile to force reconfigure
*** removing libdecnumber/Makefile to force reconfigure
*** removing fixincludes/Makefile to force reconfigure
*** removing gcc/Makefile to force reconfigure
*** removing libcc1/Makefile to force reconfigure
*** removing lto-plugin/Makefile to force reconfigure
checking for bison... bison -y
checking for bison... bison
checking for gm4... no
checking for gnum4... no
checking for m4... m4
checking for flex... flex
checking for flex... flex
checking for makeinfo... makeinfo
checking for expect... no
checking for runtest... no
checking for ar... ar
checking for as... as
checking for dlltool... no
checking for ld... ld
checking for lipo... no
checking for nm... nm
checking for ranlib... ranlib
checking for strip... strip
checking for windres... no
checking for windmc... no
checking for objcopy... objcopy
checking for objdump... objdump
checking for otool... no
checking for readelf... readelf
checking for riscv64-unknown-elf-cc... no
checking for riscv64-unknown-elf-gcc... no
checking for riscv64-unknown-elf-c++... no
checking for riscv64-unknown-elf-g++... no
checking for riscv64-unknown-elf-cxx... no
checking for riscv64-unknown-elf-gxx... no
checking for riscv64-unknown-elf-gcc... no
checking for riscv64-unknown-elf-gfortran... no
checking for riscv64-unknown-elf-gccgo... no
checking for riscv64-unknown-elf-gdc... no
checking for ar... /opt/riscv64b/riscv64-unknown-elf/bin/ar
checking for as... /opt/riscv64b/riscv64-unknown-elf/bin/as
checking for dlltool... no
checking for riscv64-unknown-elf-dlltool... no
checking for ld... /opt/riscv64b/riscv64-unknown-elf/bin/ld
checking for lipo... no
checking for riscv64-unknown-elf-lipo... no
checking for nm... /opt/riscv64b/riscv64-unknown-elf/bin/nm
checking for objcopy... /opt/riscv64b/riscv64-unknown-elf/bin/objcopy
checking for objdump... /opt/riscv64b/riscv64-unknown-elf/bin/objdump
checking for otool... no
checking for riscv64-unknown-elf-otool... no
checking for ranlib... /opt/riscv64b/riscv64-unknown-elf/bin/ranlib
checking for readelf... /opt/riscv64b/riscv64-unknown-elf/bin/readelf
checking for strip... /opt/riscv64b/riscv64-unknown-elf/bin/strip
checking for windres... no
checking for riscv64-unknown-elf-windres... no
checking for windmc... no
checking for riscv64-unknown-elf-windmc... no
checking where to find the target ar... pre-installed in /opt/riscv64b/riscv64-unknown-elf/bin
checking where to find the target as... pre-installed in /opt/riscv64b/riscv64-unknown-elf/bin
checking where to find the target cc... just compiled
checking where to find the target c++... just compiled
checking where to find the target c++ for libstdc++... just compiled
checking where to find the target dlltool... pre-installed
checking where to find the target gcc... just compiled
checking where to find the target gfortran... just compiled
checking where to find the target gccgo... pre-installed
checking where to find the target gdc... pre-installed
checking where to find the target ld... pre-installed in /opt/riscv64b/riscv64-unknown-elf/bin
checking where to find the target lipo... pre-installed
checking where to find the target nm... pre-installed in /opt/riscv64b/riscv64-unknown-elf/bin
checking where to find the target objcopy... pre-installed in /opt/riscv64b/riscv64-unknown-elf/bin
checking where to find the target objdump... pre-installed in /opt/riscv64b/riscv64-unknown-elf/bin
checking where to find the target otool... pre-installed
checking where to find the target ranlib... pre-installed in /opt/riscv64b/riscv64-unknown-elf/bin
checking where to find the target readelf... pre-installed in /opt/riscv64b/riscv64-unknown-elf/bin
checking where to find the target strip... pre-installed in /opt/riscv64b/riscv64-unknown-elf/bin
checking where to find the target windres... pre-installed
checking where to find the target windmc... pre-installed
checking whether to enable maintainer-specific portions of Makefiles... no
configure: creating ./config.status
config.status: creating Makefile_

**Comment by ptomsich** [comment]
Neither bitmanip specific, nor has there been any activity on this for over a year.
Closing.
