### ISSUE TITLE
Possible error in clzw/ctzw implementation

### ISSUE THREAD

**Issue by kropotin4** [riscv/riscv-bitmanip#78]
Case: 
1) clzw/ctzw insns in rvb_bitcnt.
2) arg (rs1): 0x0
The correct result (as it seems to me and test 46424 in asmtests/auto/test.S): 0x20 
The actual result: 0x40

if replace:
   if (wmode)
	data = data & 32'h FFFFFFFF;
and
   if (czmode)
	data = (data-1) & ~data;

will be 0x20.

**Comment by clairexen** [comment]
uh, that's embarrassing. ;) thanks for pointing this issue out. fixed it now.
