### ISSUE TITLE
 Enabling and disabling some bitmanip instructions 

### ISSUE THREAD

**Issue by NazerkeT** [riscv/riscv-bitmanip#80]
Hi there,
I am a newbie in computer architecture and for the present, I have finished implementing Zbb, Zbp, Zbs, Zbe groups of Bit Extension on CVA6(Ariane), and heading towards simulating and running them with benchmarks. So, as long as I did not implement the full bitmanip, I am wondering whether should I configure spike and riscv-gnu-toolchain compilers for switching on and off support for some instructions. Could you advise me on this, please?

Thanks,
Best wishes,

**Comment by kdockser** [comment]
Sub-extensions (e.g., Zba, Zbb, etc.) are implemented as all-or-none. You cannot support them à la carte. We try to keep related instructions together, and in some cases will create smaller sub-extensions; this is especially in the case where one extension, Crypto for example, wants to include part of a sub-extension from another extension, Zbb from Bitmanip for example.
That said, none of these instructions is currently ratified and subject to change. Any tool support should be suitable labeled as experimental or something to that effect. Once ratified, the tools should be updated to the final opcodes, mnemonics and semantics.
