### ISSUE TITLE
min[u]/max[u] vs. slt[u] encoding irregularity

### ISSUE THREAD

**Issue by clairexen** [riscv/riscv-bitmanip#81]
copy&paste from mailing list (@aswaterman):

> slt is distinguished from sltu by funct3[0].
> 
> By contrast, min is distinguished from minu by funct3[1] (whereas funct3[0] is used to distinguish min from max).
> 
> Given that straightforward implementations will use the slt computation to drive the min/max mux, would it not make sense to swap funct3[0] with funct3[1] for min[u]/max[u]?

**Comment by pdonahue-ventana** [comment]
Hasn't this been addressed?

**Comment by aswaterman** [comment]
Yes, by #88.
