### ISSUE TITLE
Get rid of subu.w, swap args on addu.w

### ISSUE THREAD

**Issue by clairexen** [riscv/riscv-bitmanip#83]
There's the proposal to remove subu.w and change addu.w so that rs1 is the argument being zero-extended instead of rs2. This way the addu.w argument semantic would match sh?addu.w and slliu.w.

**Comment by jim-wilson** [comment]
Someone should do a study to see how this affects code size and performance.  Preferably by modifying a compiler and comparing the results with and without the change.

**Comment by Rolfy360** [comment]
Suggest that addu.w can be changed to addu.wx
With this format,
“addu.wx rd, rs1, rs2” means rs1 is word-size and rs2 is xlen.
Borrow this idea from vector extension.

**Comment by pdonahue-ventana** [comment]
@aswaterman: I think that you addressed this so should it be closed?

**Comment by aswaterman** [comment]
Yes, closed by #89
