### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by eroom1966** [riscv/riscv-bitmanip#9]
@cliffordwolf 
Hi Clifford, 
I have a query regarding the documented behavior for fsl, the text says that 
The fsl rd, rs1, rs2, rs3 instruction creates a 2 x XLEN word by concatenating rs1 and rs3
(with rs1 in the MSB half)
from the pseudo code, it looks as though rs1 is in the lower half.
can you clarify which is correct ?
Thx
Lee

**Comment by cliffordwolf** [comment]
I think I know what the misunderstanding is: FSL returns the _MSB_ half of the shift result, not the LSB half. If you'd define FSL as returning the _LSB_ half of the shift result then the halfs would be swapped. Quoting the FSL spec:

> [..] and then writes the MSB half of the result to rd.

**Comment by eroom1966** [comment]
aha, RTFM (more than once anyway) thanks
I will close this issue
